import { AccountType } from '../interfaces/accounting.interface';

export interface SeedAccount {
  accountNumber: string;
  label: string;
  type: AccountType;
  accountClass: string;
  parentAccountNumber?: string;
  isSystem: boolean;
}

/**
 * Plan comptable SYSCOHADA standard pour GESTMONEY
 * 50+ comptes pertinents pour une plateforme Mobile Money
 */
export const SYSCOHADA_CHART_OF_ACCOUNTS: SeedAccount[] = [
  // ─── CLASSE 1 — Capitaux ──────────────────────────────────────────────────
  {
    accountNumber: '10',
    label: 'Capital et réserves',
    type: 'CAPITAL',
    accountClass: 'CLASSE_1',
    isSystem: true,
  },
  {
    accountNumber: '101',
    label: 'Capital social',
    type: 'CAPITAL',
    accountClass: 'CLASSE_1',
    parentAccountNumber: '10',
    isSystem: true,
  },
  {
    accountNumber: '106',
    label: 'Réserves',
    type: 'CAPITAL',
    accountClass: 'CLASSE_1',
    parentAccountNumber: '10',
    isSystem: true,
  },
  {
    accountNumber: '12',
    label: 'Résultat de l\'exercice',
    type: 'CAPITAL',
    accountClass: 'CLASSE_1',
    isSystem: true,
  },
  {
    accountNumber: '120',
    label: 'Résultat net de l\'exercice (bénéfice)',
    type: 'CAPITAL',
    accountClass: 'CLASSE_1',
    parentAccountNumber: '12',
    isSystem: true,
  },
  {
    accountNumber: '129',
    label: 'Résultat net de l\'exercice (perte)',
    type: 'CAPITAL',
    accountClass: 'CLASSE_1',
    parentAccountNumber: '12',
    isSystem: true,
  },
  {
    accountNumber: '16',
    label: 'Emprunts et dettes financières',
    type: 'PASSIF',
    accountClass: 'CLASSE_1',
    isSystem: true,
  },
  {
    accountNumber: '164',
    label: 'Emprunts auprès des établissements de crédit',
    type: 'PASSIF',
    accountClass: 'CLASSE_1',
    parentAccountNumber: '16',
    isSystem: true,
  },

  // ─── CLASSE 2 — Immobilisations ──────────────────────────────────────────
  {
    accountNumber: '22',
    label: 'Terrains',
    type: 'ACTIF',
    accountClass: 'CLASSE_2',
    isSystem: true,
  },
  {
    accountNumber: '23',
    label: 'Bâtiments',
    type: 'ACTIF',
    accountClass: 'CLASSE_2',
    isSystem: true,
  },
  {
    accountNumber: '24',
    label: 'Matériel et mobilier',
    type: 'ACTIF',
    accountClass: 'CLASSE_2',
    isSystem: true,
  },
  {
    accountNumber: '26',
    label: 'Titres de participation',
    type: 'ACTIF',
    accountClass: 'CLASSE_2',
    isSystem: true,
  },

  // ─── CLASSE 3 — Stocks ───────────────────────────────────────────────────
  {
    accountNumber: '37',
    label: 'Stocks divers',
    type: 'ACTIF',
    accountClass: 'CLASSE_3',
    isSystem: true,
  },
  {
    accountNumber: '370',
    label: 'Stock SIM / matériel agents',
    type: 'ACTIF',
    accountClass: 'CLASSE_3',
    parentAccountNumber: '37',
    isSystem: true,
  },

  // ─── CLASSE 4 — Tiers ────────────────────────────────────────────────────
  {
    accountNumber: '40',
    label: 'Fournisseurs et comptes rattachés',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    isSystem: true,
  },
  {
    accountNumber: '401',
    label: 'Fournisseurs',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '40',
    isSystem: true,
  },
  {
    accountNumber: '408',
    label: 'Fournisseurs — factures non parvenues',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '40',
    isSystem: true,
  },
  {
    accountNumber: '41',
    label: 'Clients et comptes rattachés',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    isSystem: true,
  },
  {
    accountNumber: '411',
    label: 'Clients',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '41',
    isSystem: true,
  },
  {
    accountNumber: '419',
    label: 'Clients créditeurs — avances reçues',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '41',
    isSystem: true,
  },
  {
    accountNumber: '42',
    label: 'Personnel et comptes rattachés',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    isSystem: true,
  },
  {
    accountNumber: '421',
    label: 'Personnel — rémunérations dues (agents)',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '42',
    isSystem: true,
  },
  {
    accountNumber: '44',
    label: 'État et collectivités publiques',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    isSystem: true,
  },
  {
    accountNumber: '447',
    label: 'État — impôts et taxes',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '44',
    isSystem: true,
  },
  {
    accountNumber: '4471',
    label: 'TVA collectée',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '447',
    isSystem: true,
  },
  {
    accountNumber: '4472',
    label: 'TVA déductible',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    parentAccountNumber: '447',
    isSystem: true,
  },
  {
    accountNumber: '46',
    label: 'Associés et groupe',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    isSystem: true,
  },
  {
    accountNumber: '47',
    label: 'Débiteurs et créditeurs divers',
    type: 'TIERS',
    accountClass: 'CLASSE_4',
    isSystem: true,
  },

  // ─── CLASSE 5 — Trésorerie ────────────────────────────────────────────────
  {
    accountNumber: '52',
    label: 'Banques et établissements financiers',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    isSystem: true,
  },
  {
    accountNumber: '521',
    label: 'Banque — compte courant',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '52',
    isSystem: true,
  },
  {
    accountNumber: '57',
    label: 'Caisse',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    isSystem: true,
  },
  {
    accountNumber: '571',
    label: 'Caisse principale',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '57',
    isSystem: true,
  },
  {
    accountNumber: '58',
    label: 'Floats Mobile Money — opérateurs',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    isSystem: true,
  },
  {
    accountNumber: '581',
    label: 'Float Orange Money',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '582',
    label: 'Float MTN MoMo',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '583',
    label: 'Float Wave',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '584',
    label: 'Float Moov Money',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '585',
    label: 'Float Airtel Money',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '586',
    label: 'Float Free Money',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '587',
    label: 'Float T-Money (Togocel)',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '588',
    label: 'Float M-Pesa',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    parentAccountNumber: '58',
    isSystem: true,
  },
  {
    accountNumber: '59',
    label: 'Provisions pour dépréciation des comptes financiers',
    type: 'TRESORERIE',
    accountClass: 'CLASSE_5',
    isSystem: true,
  },

  // ─── CLASSE 6 — Charges ───────────────────────────────────────────────────
  {
    accountNumber: '60',
    label: 'Achats et variations de stocks',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '61',
    label: 'Transports',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '62',
    label: 'Services extérieurs A',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '621',
    label: 'Sous-traitance générale',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '62',
    isSystem: true,
  },
  {
    accountNumber: '627',
    label: 'Commissions versées aux agents',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '62',
    isSystem: true,
  },
  {
    accountNumber: '628',
    label: 'Frais bancaires et charges assimilées',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '62',
    isSystem: true,
  },
  {
    accountNumber: '63',
    label: 'Services extérieurs B',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '64',
    label: 'Impôts et taxes',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '641',
    label: 'Impôts et taxes directs',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '64',
    isSystem: true,
  },
  {
    accountNumber: '65',
    label: 'Autres charges',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '658',
    label: 'Autres charges — pertes diverses',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '65',
    isSystem: true,
  },
  {
    accountNumber: '66',
    label: 'Charges de personnel',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '661',
    label: 'Rémunérations directes versées au personnel',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '66',
    isSystem: true,
  },
  {
    accountNumber: '67',
    label: 'Frais financiers et charges assimilées',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    isSystem: true,
  },
  {
    accountNumber: '671',
    label: 'Intérêts des emprunts',
    type: 'CHARGE',
    accountClass: 'CLASSE_6',
    parentAccountNumber: '67',
    isSystem: true,
  },

  // ─── CLASSE 7 — Produits ──────────────────────────────────────────────────
  {
    accountNumber: '70',
    label: 'Ventes de marchandises et produits fabriqués',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    isSystem: true,
  },
  {
    accountNumber: '706',
    label: 'Commissions reçues sur opérations Mobile Money',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    parentAccountNumber: '70',
    isSystem: true,
  },
  {
    accountNumber: '707',
    label: 'Frais de service facturés aux clients',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    parentAccountNumber: '70',
    isSystem: true,
  },
  {
    accountNumber: '75',
    label: 'Autres produits',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    isSystem: true,
  },
  {
    accountNumber: '758',
    label: 'Autres produits divers',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    parentAccountNumber: '75',
    isSystem: true,
  },
  {
    accountNumber: '77',
    label: 'Revenus financiers et produits assimilés',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    isSystem: true,
  },
  {
    accountNumber: '771',
    label: 'Intérêts de prêts et de dépôts',
    type: 'PRODUIT',
    accountClass: 'CLASSE_7',
    parentAccountNumber: '77',
    isSystem: true,
  },
];

/**
 * Mapping opérateur Mobile Money → numéro de compte Float
 */
export const OPERATOR_FLOAT_ACCOUNT: Record<string, string> = {
  ORANGE_MONEY: '581',
  MTN_MOMO: '582',
  WAVE: '583',
  MOOV_MONEY: '584',
  AIRTEL_MONEY: '585',
  FREE_MONEY: '586',
  TMONEY: '587',
  M_PESA: '588',
};
