// ─── Types SYSCOHADA ──────────────────────────────────────────────────────────

export type AccountType =
  | 'ACTIF'
  | 'PASSIF'
  | 'CHARGE'
  | 'PRODUIT'
  | 'TRESORERIE'
  | 'CAPITAL'
  | 'TIERS';

export type AccountClass =
  | 'CLASSE_1' // Capitaux
  | 'CLASSE_2' // Immobilisations
  | 'CLASSE_3' // Stocks
  | 'CLASSE_4' // Tiers
  | 'CLASSE_5' // Trésorerie
  | 'CLASSE_6' // Charges
  | 'CLASSE_7' // Produits
  | 'CLASSE_8' // Comptes spéciaux
  | 'CLASSE_9'; // Comptabilité analytique

export type FiscalYearStatus = 'OPEN' | 'CLOSED' | 'LOCKED';

export type ReconciliationStatus = 'PENDING' | 'RECONCILED' | 'DISPUTED';

// ─── Compte comptable ─────────────────────────────────────────────────────────

export interface IChartOfAccount {
  id: string;
  tenantId: string;
  accountNumber: string;
  label: string;
  type: AccountType;
  accountClass: AccountClass;
  parentAccountNumber?: string;
  currency: string;
  isActive: boolean;
  isSystem: boolean; // Compte SYSCOHADA standard non supprimable
  createdAt: Date;
  updatedAt: Date;
}

// ─── Exercice fiscal ──────────────────────────────────────────────────────────

export interface IFiscalYear {
  id: string;
  tenantId: string;
  label: string;
  startDate: Date;
  endDate: Date;
  status: FiscalYearStatus;
  closedAt?: Date;
  closedBy?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Écriture comptable (Ligne de journal) ────────────────────────────────────

export interface JournalLine {
  accountNumber: string;
  label: string;
  debit: string; // Decimal string pour éviter les erreurs d'arrondi
  credit: string;
  currency?: string;
  exchangeRate?: number;
  amountXof?: string; // Montant converti en XOF
}

// ─── Écriture de journal ──────────────────────────────────────────────────────

export interface IJournalEntry {
  id: string;
  tenantId: string;
  fiscalYearId: string;
  reference: string;
  date: Date;
  description: string;
  lines: IJournalLine[];
  transactionId?: string;
  agentId?: string;
  costCenterId?: string;
  isAutoGenerated: boolean;
  isReconciled: boolean;
  reconciliationRef?: string;
  createdBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface IJournalLine {
  id: string;
  journalEntryId: string;
  accountNumber: string;
  label: string;
  debit: string;
  credit: string;
  currency: string;
  exchangeRate: number;
  amountXof: string;
}

// ─── Balance / Grand livre ────────────────────────────────────────────────────

export interface TrialBalanceLine {
  accountNumber: string;
  label: string;
  type: AccountType;
  totalDebit: string;
  totalCredit: string;
  balance: string; // debit - credit (positif = solde débiteur)
  balanceType: 'DEBITEUR' | 'CREDITEUR';
}

export interface ITrialBalance {
  fiscalYearId: string;
  asOfDate: Date;
  lines: TrialBalanceLine[];
  totalDebit: string;
  totalCredit: string;
  isBalanced: boolean;
}

// ─── Compte de résultat ───────────────────────────────────────────────────────

export interface IncomeStatementLine {
  accountNumber: string;
  label: string;
  montant: string;
}

export interface IIncomeStatement {
  fiscalYearId: string;
  period: { startDate: Date; endDate: Date };
  produits: IncomeStatementLine[];
  charges: IncomeStatementLine[];
  totalProduits: string;
  totalCharges: string;
  resultatNet: string; // positif = bénéfice, négatif = perte
}

// ─── Bilan ────────────────────────────────────────────────────────────────────

export interface BalanceSheetItem {
  accountNumber: string;
  label: string;
  montant: string;
}

export interface IBalanceSheet {
  fiscalYearId: string;
  asOfDate: Date;
  actif: {
    immobilisations: BalanceSheetItem[];
    stocks: BalanceSheetItem[];
    creances: BalanceSheetItem[];
    tresorerie: BalanceSheetItem[];
    totalActif: string;
  };
  passif: {
    capitaux: BalanceSheetItem[];
    dettes: BalanceSheetItem[];
    totalPassif: string;
  };
  isBalanced: boolean;
  difference: string;
}

// ─── Flux de trésorerie ───────────────────────────────────────────────────────

export interface ICashFlow {
  fiscalYearId: string;
  period: { startDate: Date; endDate: Date };
  operatingActivities: Array<{ label: string; montant: string }>;
  investingActivities: Array<{ label: string; montant: string }>;
  financingActivities: Array<{ label: string; montant: string }>;
  netCashFromOperations: string;
  netCashFromInvesting: string;
  netCashFromFinancing: string;
  netCashVariation: string;
  openingCash: string;
  closingCash: string;
}

// ─── Centre de coûts ──────────────────────────────────────────────────────────

export interface ICostCenter {
  id: string;
  tenantId: string;
  code: string;
  label: string;
  isActive: boolean;
  createdAt: Date;
}

// ─── Rapprochement bancaire ───────────────────────────────────────────────────

export interface IReconciliation {
  id: string;
  tenantId: string;
  journalEntryId: string;
  transactionId?: string;
  bankReference?: string;
  status: ReconciliationStatus;
  reconciledAt?: Date;
  reconciledBy?: string;
  notes?: string;
  createdAt: Date;
}
