// ============================================================
// HOOK — COMPTABILITÉ SYSCOHADA (React Query + API réelle)
// Endpoints backend: /accounting/* (voir accounting.controller.ts)
//
// IMPORTANT : aucun fallback sur des données de démonstration.
// Il s'agit de comptabilité — afficher de faux soldes ou de fausses
// écritures serait gravement trompeur. En cas d'erreur, la requête
// échoue et la page affiche un état d'erreur explicite.
// ============================================================
import { useQuery } from '@tanstack/react-query';
import api from '@/lib/api';

// ─── Types (calqués sur apps/api/src/accounting/interfaces) ──────────────────

export type StatutExercice = string;

export interface ExerciceFiscal {
  id: string;
  tenantId: string;
  label: string;
  startDate: string;
  endDate: string;
  status: StatutExercice;
  closedAt?: string;
  closedBy?: string;
}

export interface CompteChart {
  id: string;
  code: string;
  name: string;
  type: string;
  level: number;
  normalBalance: 'DEBIT' | 'CREDIT';
  isActive: boolean;
  parentId?: string | null;
}

export interface LigneEcriture {
  id: string;
  journalEntryId: string;
  accountNumber: string;
  label: string;
  debit: string;
  credit: string;
  currency?: string;
  amountXof?: string;
}

export interface EcritureJournal {
  id: string;
  reference: string;
  date: string;
  description: string;
  fiscalYearId: string;
  lines: LigneEcriture[];
  isAutoGenerated: boolean;
  isReconciled: boolean;
  transactionId?: string;
  createdAt: string;
}

export interface JournalPage {
  data: EcritureJournal[];
  total: number;
  page: number;
  limit: number;
}

export interface LigneBalance {
  accountNumber: string;
  label: string;
  type: string;
  totalDebit: string;
  totalCredit: string;
  balance: string;
  balanceType: 'DEBITEUR' | 'CREDITEUR';
}

export interface BalanceVerification {
  fiscalYearId: string;
  asOfDate: string;
  lines: LigneBalance[];
  totalDebit: string;
  totalCredit: string;
  isBalanced: boolean;
}

export interface LigneResultat {
  accountNumber: string;
  label: string;
  montant: string;
}

export interface CompteResultat {
  fiscalYearId: string;
  period: { startDate: string; endDate: string };
  produits: LigneResultat[];
  charges: LigneResultat[];
  totalProduits: string;
  totalCharges: string;
  resultatNet: string;
}

export interface PosteBilan {
  accountNumber: string;
  label: string;
  montant: string;
}

export interface Bilan {
  fiscalYearId: string;
  asOfDate: string;
  actif: {
    immobilisations: PosteBilan[];
    stocks: PosteBilan[];
    creances: PosteBilan[];
    tresorerie: PosteBilan[];
    totalActif: string;
  };
  passif: {
    capitaux: PosteBilan[];
    dettes: PosteBilan[];
    totalPassif: string;
  };
  isBalanced: boolean;
  difference: string;
}

// ─── Clés de cache ───────────────────────────────────────────────────────────

export const COMPTA_KEYS = {
  all: ['comptabilite'] as const,
  exercices: () => ['comptabilite', 'exercices'] as const,
  chart: () => ['comptabilite', 'chart'] as const,
  journal: (p: JournalParams) => ['comptabilite', 'journal', p] as const,
  balance: (fy?: string) => ['comptabilite', 'balance', fy ?? 'all'] as const,
  resultat: (fy?: string) => ['comptabilite', 'resultat', fy ?? 'all'] as const,
  bilan: (fy?: string) => ['comptabilite', 'bilan', fy ?? 'all'] as const,
};

export interface JournalParams {
  fiscalYearId?: string;
  accountNumber?: string;
  startDate?: string;
  endDate?: string;
  page?: number;
  limit?: number;
}

/** Retire les clés vides pour ne pas envoyer de query params invalides (DTO strict côté API). */
function nettoyer(params: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null && v !== '') out[k] = v;
  }
  return out;
}

// ─── Requêtes ────────────────────────────────────────────────────────────────

/** Exercices fiscaux du tenant — GET /accounting/fiscal-year */
export function useExercicesFiscaux() {
  return useQuery({
    queryKey: COMPTA_KEYS.exercices(),
    queryFn: async (): Promise<ExerciceFiscal[]> => {
      const res = await api.get('/accounting/fiscal-year');
      return Array.isArray(res.data) ? res.data : res.data?.data ?? [];
    },
  });
}

/** Plan comptable SYSCOHADA — GET /accounting/chart */
export function usePlanComptable() {
  return useQuery({
    queryKey: COMPTA_KEYS.chart(),
    queryFn: async (): Promise<CompteChart[]> => {
      const res = await api.get('/accounting/chart');
      return Array.isArray(res.data) ? res.data : res.data?.data ?? [];
    },
  });
}

/** Écritures du journal (grand livre) — GET /accounting/journal */
export function useJournal(params: JournalParams = {}) {
  return useQuery({
    queryKey: COMPTA_KEYS.journal(params),
    queryFn: async (): Promise<JournalPage> => {
      const res = await api.get('/accounting/journal', {
        params: nettoyer({ limit: 50, page: 1, ...params }),
      });
      const d = res.data;
      if (Array.isArray(d)) {
        return { data: d, total: d.length, page: 1, limit: d.length };
      }
      return {
        data: d?.data ?? [],
        total: Number(d?.total ?? 0),
        page: Number(d?.page ?? 1),
        limit: Number(d?.limit ?? 50),
      };
    },
  });
}

/** Balance de vérification — GET /accounting/trial-balance */
export function useBalanceVerification(fiscalYearId?: string) {
  return useQuery({
    queryKey: COMPTA_KEYS.balance(fiscalYearId),
    queryFn: async (): Promise<BalanceVerification> => {
      const res = await api.get('/accounting/trial-balance', {
        params: nettoyer({ fiscalYearId }),
      });
      return res.data;
    },
  });
}

/** Compte de résultat — GET /accounting/income-statement */
export function useCompteResultat(fiscalYearId?: string) {
  return useQuery({
    queryKey: COMPTA_KEYS.resultat(fiscalYearId),
    queryFn: async (): Promise<CompteResultat> => {
      const res = await api.get('/accounting/income-statement', {
        params: nettoyer({ fiscalYearId }),
      });
      return res.data;
    },
  });
}

/** Bilan actif / passif — GET /accounting/balance-sheet */
export function useBilan(fiscalYearId?: string) {
  return useQuery({
    queryKey: COMPTA_KEYS.bilan(fiscalYearId),
    queryFn: async (): Promise<Bilan> => {
      const res = await api.get('/accounting/balance-sheet', {
        params: nettoyer({ fiscalYearId }),
      });
      return res.data;
    },
  });
}

// ─── Utilitaires d'affichage ─────────────────────────────────────────────────

/** Les montants arrivent en chaînes décimales ("1234.00") pour éviter les arrondis. */
export function versNombre(v: string | number | null | undefined): number {
  const n = typeof v === 'number' ? v : parseFloat(String(v ?? '0'));
  return Number.isFinite(n) ? n : 0;
}
